### ISSUE TITLE
[Question] Speedup compared to SB3

### ISSUE THREAD

**Issue by thomashirtz** [araffin/sbx#31]
### Question

One of the main feature of JAX compared to torch or TF is the speed. Would it be possible to showcase the speedup obtained using SBX compared to SB3 on environment that are fully jitted/not fully jitted ? It would give insights about the speedup increased and if it is worth switching from one library to the other.  

Thanks !

### Checklist

- [x] I have read the [documentation](https://stable-baselines3.readthedocs.io/en/master/) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/DLR-RM/stable-baselines3/issues) in the repo (**required**)

**Comment by araffin** [comment]
> Would it be possible to showcase the speedup obtained using SBX compared to SB3 on environment that are fully jitted/not fully jitted ?

See https://wandb.ai/openrlbenchmark/sb3/reports/SB3-vs-SBX--VmlldzoyOTczNDg2 for a partial report.
You can already do comparison using openrlbenchmark runs (both SB3 and SBX are logged).

For runtime reports, you can have a look at https://arxiv.org/abs/2310.05808
Please note that you should use cpu device with PPO when not using CNN.

SBX still uses SB3 numpy replay buffer, so it is mostly helpful when speeding up gradient update (which is the current bottleneck), jitting the env will give an additional boost if it is the bottleneck.

Related to https://github.com/araffin/sbx/issues/27
