### ISSUE TITLE
[Question] MaskablePPO support

### ISSUE THREAD

**Issue by GuillermoHijano** [araffin/sbx#34]
Hello, 

I have a question about SBX. I am using maskablePPO from SB3 contrib because in my RL problem action masking is really important. I have found out about SBX library which seems to be very promising for speeding up computation time. My question is: does SBX support maskablePPO from SB3 contrib? 

Thank you very much in advance for your help,
Best,
G.

**Comment by araffin** [comment]
> My question is: does SBX support maskablePPO from SB3 contrib?

it does not.
But you could adapt current SBX to include the modifications we have in SB3 contrib.
