### ISSUE TITLE
[Feature Request] Passing custom activation functon in policy_kwargs

### ISSUE THREAD

**Issue by paolodelia99** [araffin/sbx#37]
### 🚀 Feature

Possibility to pass a flax (from the [`flax.linen.activation`](https://flax.readthedocs.io/en/latest/api_reference/flax.linen/activation_functions.html) module) activation function when creating a `sbx` model, through the `policy_kwargs` argument.

### Motivation

In the current implementation of `sbx`, users are unable to pass custom activation functions when creating a model. This limitation restricts flexibility and may not suit all users' needs.

### Pitch

Example:

```python
policy_kwargs = dict(activation_fn=my_custom_activation_fn, net_arch=dict(pi=[64, 64], qf=[64, 64]))

model = TD3("MlpPolicy",
                       env,
                      policy_kwargs=policy_kwargs,
                      verbose=1)
```

### Idea on how to implement it 

Add attribute `activation_fn` to the underlying classes that are composing the policy (like in Critic and Actor in [`t3d/policy.py`](https://github.com/araffin/sbx/blob/db6120bdd4c630b7c141fe091e5d469626aa3aa4/sbx/td3/policies.py))

**Comment by araffin** [comment]
Hello,
sounds reasonable, would you contribute such feature?

**Comment by paolodelia99** [comment]
Sure.
